[global]
port = 720
dbPrefix = "romiChan"
lang = "en_US"
commandPrefix = "/"
dirs = [
  "modules",
  "modules/base",
  "modules/platform",
  "modules/test",
  "modules/tools",
  "modules/amuse",
]
noColor = false
level = 25

[adapter.cmd-test]
extends = "cmd"
master = 2333
nickname = "Kotarou"
age = 18
sex = "male"
self-id = 720

[plugin.helper]
content = "test menu"

[build]
banner = "/**\n* @Package %name%\n* @Version %version%\n* @Author %author%\n* @Copyright 2024-2025 Hotaru. All rights reserved.\n* @License %license%\n* @Link https://github.com/kotorijs/kotori\n* @Date %date%\n*/"
