[global]
port = 721
lang = "zh_CN"
command-prefix = "/"
dirs = []
noColor = false
level = 20


[adapter.cmd-test]
extends = "cmd"
master = 2333
nickname = "Kotarou"
age = 18
sex = "male"
self-id = 720

[adapter.sena]
extends = "onebot"
master = 3324656453
mode = "ws-reverse"
port = 23

[adapter.mizuki]
extends = "sandbox"
master = 899110018
port = 233

[adapter.romi]
extends = "minecraft"
command-prefix = "~"
master = 2333
template = "<§b§l%nickname%§f> §a%msg%§f"
nickname = "Romi"

[plugin.helper]
content = "请发送 /help"

[plugin.filter]
mode = 'exclude'
list = ['kotori-plugin-adapter-{onebot,minecraft,qq}']
