name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: $MAJOR.$MINOR.$PATCH
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'kind/feature'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
  - title: Documentation
    labels:
      - doc
  - title: 'Refatcory'
    labels:
      - 'refactory'
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid
  - chore
  - style
change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## What’s Changed
  $CHANGES
