name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install packages
        run: pnpm install
      - name: Build packages
        run: pnpm build
      - name: Zip packages
        run: pnpm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          files: |
            'kotori-bot-**.tgz'
