name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Clone submodules
        run: |
          git submodule init
          git submodule update
      - name: Install packages
        run: pnpm install --no-frozen-lockfile
      - name: Build packages
        run: pnpm build
      - name: Zip packages
        run: pnpm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kotori-bot-root
          path: |
            kotori-bot-*.tgz
